name = "abalonecove-chat"
main = "index.ts"
compatibility_date = "2026-04-01"

[[routes]]
pattern = "abalonecove.org/api/chat"
zone_name = "abalonecove.org"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5bff26b234bf4a21bfb8d82a41501f7a"

[[kv_namespaces]]
binding = "KB"
id = "e7d75fdbd052447fb7a161f23af1294c"
